### ISSUE TITLE
Are nested routes similar to react-router's `<Outlet />` supported?

### ISSUE THREAD

**Issue by altierawr** [santino/react-concurrent-router#6]
I'm looking to render child routes inside parent components in a way where the parent component is also rendered, similarly to how react-router's `<Outlet />` works or similar to how the official relay issue-tracker handles it via just the `children` prop; [see here](https://github.com/relayjs/relay-examples/blob/d9689a8f9ab3b07f16f2fcec9ed3e63965b9b8e9/issue-tracker/src/Root.js#L35.).

I cannot find an example of this anywhere in the docs, and your own issue-tracker example just uses the `IssueList` [directly as a child component](https://github.com/santino/react-concurrent-router-examples/blob/75b5d97323f3ef6f32982131b10505110cae2be4/issue-tracker-relay-experimental/src/pages/Home.js#L115). Is what I'm describing possible with this library?

**Comment by santino** [comment]
Hi @expesh ,
I am extremely sorry, I've just noticed this issue and I see it has been open for months.

Currently, React Concurrent Router does not support this functionality.
If you are still interested in it, I would be happy to hear a real world use case for it, in order to potentially consider adding a new feature.

**Comment by altierawr** [comment]
Hi,

Sorry for the delay with the reply.

I personally do not have a need for this anymore as I ended up creating my own router with this functionality. I do not remember the exact use case I had, but it was something where I wanted to render some views where multiple routes shared the same parent view or a common component from a parent route.

For example, you could have a route /myroute which has a tab navigation which links to /myroute/a, /myroute/b and so on. In this case I would like to have a component for the route /myroute, which has the tab navigation, and then dynamically render one of the child routes inside the parent component, so that I have to only put the tab navigation in one place (the /myroute component), and this way the tab navigation wouldn't have to re-mount either.

Feel free to close the issue if you feel like there's no need for this feature in your library (and as I said, I do not have a need for it anymore).

**Comment by santino** [comment]
Thanks for coming back and great to hear you decided to build a custom solution tailored to your application.

My personal view is that routing should be managing page navigation and more specifically which page component to render and how to provide the required data to it.
When you have a single page containing several tabs, these elements do not represent a page on their own but are instead composing this single page.

I have a similar use case and rather than adding complexity to a route or even nesting multiple routes, I am solving this with query parameters (or they could be named parameters etc).

In this case, my tab component is responsible for reading the query parameters and identifying which tab should be rendered/mounted; and it all happens within a single page and route.

React Concurrent Router supports this with the `useSearchParams` hook, which can be used to push the selected tab name to query parameters and read from query parameters which tab name was selected.

This is, again, just my personal flavor and I am sharing it here in case it could be useful to future readers.
